Repository Unleash/unleash, pull requests merged in 2023-07, with the labels that each got.

#4182 docs: add description to requests per seconds schemas
  src/lib/openapi/meta-schema-rules.test.ts
  src/lib/openapi/spec/requests-per-second-schema.ts
  src/lib/openapi/spec/requests-per-second-segmented-schema.ts
Labels: docs

#4196 chore: Datadog addon, ability to include source type name
  src/lib/addons/__snapshots__/datadog.test.ts.snap
  src/lib/addons/datadog-definition.ts
  src/lib/addons/datadog.test.ts
  src/lib/addons/datadog.ts
Labels: improvement

#4191 docs: Update proxy hosting to point to Frontend API
  website/docs/topics/proxy-hosting.mdx
Labels: docs

#4335 fix: missing events in the event store
  src/lib/db/event-store.ts
Labels: bug
