Repository Unleash/unleash, pull requests merged in 2023-06, with the labels that each got.

#3953 fix: allow empty appName as it may come in the url
  src/lib/openapi/spec/create-application-schema.ts
  src/lib/routes/admin-api/metrics.test.ts
  src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Labels: bug

#3958 fix: feature not found in project yields 404
  src/lib/services/feature-toggle-service.ts
  src/lib/types/stores/feature-toggle-store.ts
  src/test/e2e/api/admin/project/features.e2e.test.ts
Labels: bug

#3979 docs: OpenAPI Client tag
  src/lib/openapi/meta-schema-rules.test.ts
  src/lib/openapi/spec/client-application-schema.ts
  src/lib/openapi/spec/client-feature-schema.ts
  src/lib/openapi/spec/client-features-query-schema.ts
  src/lib/openapi/spec/client-features-schema.test.ts
  src/lib/openapi/spec/client-features-schema.ts
  src/lib/openapi/spec/feature-schema.test.ts
  src/lib/openapi/spec/feature-strategy-schema.ts
  src/lib/openapi/spec/override-schema.ts
  src/lib/openapi/spec/variant-schema.ts
  src/lib/routes/client-api/feature.ts
  src/lib/routes/client-api/metrics.ts
  src/lib/routes/client-api/register.ts
  src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Labels: docs

#4019 feat: Separate api token roles
  src/lib/routes/admin-api/api-token.ts
  src/lib/services/access-service.ts
  src/lib/services/api-token-service.ts
  src/lib/types/permissions.ts
  src/migrations/20230619105029-new-fine-grained-api-token-permissions.js
  src/migrations/20230619110243-assign-apitoken-permissions-to-rootroles.js
  src/test/e2e/api/admin/api-token.auth.e2e.test.ts
  src/test/e2e/api/admin/api-token.e2e.test.ts
  src/test/e2e/helpers/test-helper.ts
Labels: enhancement

#4117 docs: Context api tag
  src/lib/openapi/meta-schema-rules.test.ts
  src/lib/openapi/spec/context-field-schema.ts
  src/lib/openapi/spec/context-fields-schema.ts
  src/lib/openapi/spec/legal-value-schema.ts
  src/lib/routes/admin-api/context.ts
  src/test/e2e/api/admin/state.e2e.test.ts
  src/test/e2e/api/openapi/__snapshots__/openapi.e2e.test.ts.snap
Labels: docs
