Repository Unleash/unleash, pull requests merged in 2023-01, with the labels that each got.

#2562 fix: add frontend eslint check
  .github/workflows/build_frontend_prs.yml
  frontend/package.json
  frontend/src/component/changeRequest/ChangeRequestPermissions.test.tsx
  frontend/src/component/common/MessageBanner/MessageBanner.tsx
  scripts/check-release.sh
Labels: tech-debt

#2749 fix: enforce weight precision to 1 decimal
  frontend/src/component/feature/FeatureView/FeatureVariants/FeatureEnvironmentVariants/EnvironmentVariantModal/EnvironmentVariantModal.tsx
  src/lib/schema/feature-schema.test.ts
  src/lib/schema/feature-schema.ts
Labels: bug

#2768 feat: wait for deps to be somewhat stable
  renovate.json
Labels: enhancement

#2900 fix: found an edge case exporting variants
  src/lib/services/state-service.ts
  src/test/e2e/api/admin/state.e2e.test.ts
  src/test/examples/exported3-with-default-disabled.json
Labels: bug

#2912 fix: add environment to event log card
  frontend/src/component/events/EventCard/EventCard.tsx
Labels: improvement

#2971 chore: ignore Twitter link from being checked
  .lycheeignore
Labels: docs

#3020 fix: list projects with all archived toggles
  src/lib/db/project-store.ts
  src/test/e2e/services/project-service.e2e.test.ts
Labels: bug
