Repository Unleash/unleash, pull requests merged in 2025-10, with the labels that each got.

#10703 Refactor flag filters
  frontend/src/component/onboarding/flow/ProjectOnboarding.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ColumnsMenu/ColumnsMenu.styles.ts
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ColumnsMenu/ColumnsMenu.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/FlagCreationButton/FlagCreationButton.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ImportButton/ImportButton.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeaturesColumnsMenu/ProjectFeaturesColumnsMenu.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFlagsSearch/ProjectFlagsSearch.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/formatEnvironmentColumnId.ts
  frontend/src/component/project/Project/ProjectFeatureToggles/ColumnsMenu/ColumnsMenu.styles.ts
  frontend/src/component/project/Project/ProjectFeatureToggles/ColumnsMenu/ColumnsMenu.tsx
  frontend/src/interfaces/uiConfig.ts
Labels: 👤 all-human

#10706 feat: add placeholder for empty change requests table
  frontend/src/component/changeRequest/ChangeRequests/ChangeRequests.tsx
Labels: 👤🤝🤖 half-half

#10710 feat: change "archived" flags filter placement on project flags list
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureToggles.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectFeatureTogglesHeader/ProjectFeatureTogglesHeader.tsx
  frontend/src/component/project/Project/PaginatedProjectFeatureToggles/ProjectOverviewFilters.tsx
Labels: 👤🤖 mostly-human

#10721 feat: new invoice billing page view
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoice.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoiceRow/BillingInvoiceRow.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/ConsumptionIndicator/ConsumptionIndicator.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/spec.md
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/types.ts
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoices.tsx
  frontend/src/component/common/PercentageCircle/PercentageDonut.tsx
Labels: 👤🤖 mostly-human

#10728 feat: add histogram to impact metrics
  src/lib/openapi/spec/impact-metrics-schema.ts
Labels: 🤖👤 mostly-ai

#10736 feat: allow test operation for patch
  src/lib/openapi/spec/patch-schema.ts
Labels: 👤🤖 mostly-human

#10744 feat: invoice sections
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoice.styles.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoice.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoiceFooter/BillingInvoiceFooter.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/BillingInvoiceRow/BillingInvoiceRow.tsx
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/formatCurrency.test.ts
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/formatCurrency.ts
  frontend/src/component/admin/billing/BillingInvoices/BillingInvoice/types.ts
  frontend/src/hooks/api/getters/useDetailedInvoices/useDetailedInvoices.ts
Labels: 👤🤖 mostly-human

#10746 feat: move release plans to feature environments
  src/lib/features/feature-toggle/createFeatureToggleService.ts
  src/lib/features/feature-toggle/feature-toggle-service.ts
  src/lib/features/release-plans/release-plan-read-model-type.ts
  src/lib/features/release-plans/release-plan-read-model.ts
  src/lib/features/release-plans/release-plan-store.ts
  src/lib/openapi/spec/export-result-schema.ts
  src/lib/openapi/spec/feature-environment-schema.ts
  src/lib/openapi/spec/feature-schema.ts
  src/lib/openapi/spec/feature-search-environment-schema.ts
  src/lib/openapi/spec/health-overview-schema.ts
  src/lib/openapi/spec/import-toggles-schema.ts
  src/lib/openapi/spec/project-overview-schema.ts
  src/test/fixtures/fake/fake-release-plan-read-model.ts
Labels: 👤🤝🤖 half-half

#10749 feat: implement milestone progression form
  frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/MilestoneProgressionForm/MilestoneProgressionForm.tsx
  frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/ReleasePlan.tsx
  frontend/src/component/feature/FeatureView/FeatureOverview/ReleasePlan/hooks/useMilestoneProgressionForm.ts
  frontend/src/hooks/api/actions/useMilestoneProgressionsApi/useMilestoneProgressionsApi.ts
Labels: 👤🤖 mostly-human

#10759 Improve release plan write model
  src/lib/features/release-plans/release-plan-milestone-store.ts
  src/lib/features/release-plans/release-plan-milestone.ts
Labels: 👤 all-human

#10760 fix: transition condition type
  src/lib/features/release-plans/release-plan-milestone.ts
Labels: 👤 all-human

#10762 chore: feature release plans flag
  frontend/src/interfaces/uiConfig.ts
  src/lib/features/feature-toggle/feature-toggle-service.ts
  src/lib/types/experimental.ts
  src/server-dev.ts
Labels: 👤 all-human

#10701 docs: add FAQs to 11 principles page
  website/docs/topics/feature-flags/feature-flag-best-practices.mdx
Labels: 🤖👤 mostly-ai
